name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    permissions:
      contents: write
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --bins --release --locked
          strip: true
          cross-version: 107433fa9d71d7eb506cd5bf5467bab89edb7a52
      - name: Release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: hello-rust
          target: ${{ matrix.platform.target }}
          changes-file: ""
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - runs-on: macos-latest
            target: aarch64-apple-darwin
          - runs-on: windows-latest
            target: x86_64-pc-windows-msvc
      fail-fast: false
